#ifndef COLORS_H
#define COLORS_H
#define MENU_BACKGROUND_COLOR TFT_BLACK
#define MENU_ITEM_TEXT_COLOR TFT_WHITE
#define MENU_ITEM_NUMBER_TEXT_COLOR TFT_LIGHTGREY
#define MENU_ITEM_ACTIVE_BACKGROUND TFT_MAROON
#define MENU_HEADER_TEXT_COLOR TFT_WHITE
#define MENU_HEADER_BACKGROUND TFT_MAROON
#endif //COLORS_H
